apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviewservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviewservice
  template:
    metadata:
      labels:
        app: reviewservice
    spec:
      containers:
      - name: reviewservice
        image: reviewservice
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "mongodb://mongo-service:27017/reviews" # Example database URL
        - name: DEBUG
          value: "true" # Example debug mode
---
apiVersion: v1
kind: Service
metadata:
  name: reviewservice
spec:
  type: ClusterIP
  selector:
    app: reviewservice
  ports:
  - port: 8080
    targetPort: 8080
