apiVersion: apps/v1
kind: Deployment
metadata:
  name: translationservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: translationservice
  template:
    metadata:
      labels:
        app: translationservice
    spec:
      containers:
      - name: translationservice
        image: translationservice
        env:
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: google-translate-key
              key: api-key
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: translationservice
spec:
  type: ClusterIP
  selector:
    app: translationservice
  ports:
  - port: 8080
    targetPort: 8080
